// <auto-generated />
using Final_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project.Migrations
{
    [DbContext(typeof(HobbyContext))]
    [Migration("20221129170236_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Final_Project.Models.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"), 1L, 1);

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.ToTable("about");
                });

            modelBuilder.Entity("Final_Project.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<int>("AboutId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("admin");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            AboutId = 1,
                            FirstName = "Hilbert",
                            LastName = "Perez"
                        });
                });

            modelBuilder.Entity("Final_Project.Models.AdminHobby", b =>
                {
                    b.Property<int>("AdminHobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminHobbyId"), 1L, 1);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("HobbyId")
                        .HasColumnType("int");

                    b.HasKey("AdminHobbyId");

                    b.HasIndex("AdminId");

                    b.HasIndex("HobbyId");

                    b.ToTable("AdminHobbies");

                    b.HasData(
                        new
                        {
                            AdminHobbyId = 1,
                            AdminId = 1,
                            HobbyId = 1
                        });
                });

            modelBuilder.Entity("Final_Project.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HobbyID"), 1L, 1);

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyID");

                    b.ToTable("hobby");

                    b.HasData(
                        new
                        {
                            HobbyID = 1,
                            Desc = "Art is the best",
                            HobbyName = "Art"
                        });
                });

            modelBuilder.Entity("Final_Project.Models.AdminHobby", b =>
                {
                    b.HasOne("Final_Project.Models.Admin", "admin")
                        .WithMany("AdminHobbies")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Project.Models.Hobby", "hobby")
                        .WithMany("AdminHobbies")
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");

                    b.Navigation("hobby");
                });

            modelBuilder.Entity("Final_Project.Models.Admin", b =>
                {
                    b.Navigation("AdminHobbies");
                });

            modelBuilder.Entity("Final_Project.Models.Hobby", b =>
                {
                    b.Navigation("AdminHobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
